import { EMAIL_CLIENTS, type CSSWarning, type TransformResult } from "@emailens/engine";

/**
 * Generate a self-contained HTML report file.
 */
export function generateHtmlReport(opts: {
  scores: Record<string, { score: number; errors: number; warnings: number; info: number }>;
  warnings: CSSWarning[];
  transforms?: TransformResult[];
  darkMode?: Record<string, { html: string; warnings: CSSWarning[] }>;
  originalHtml?: string;
}): string {
  const clientMap = new Map(EMAIL_CLIENTS.map((c) => [c.id, c]));

  const scoreValues = Object.values(opts.scores);
  const overallScore = scoreValues.length > 0
    ? Math.round(scoreValues.reduce((a, b) => a + b.score, 0) / scoreValues.length)
    : 0;

  const scoreColor = (s: number) => s >= 90 ? "#22c55e" : s >= 70 ? "#eab308" : "#ef4444";

  // Build client cards
  const clientCards = Object.entries(opts.scores)
    .sort(([, a], [, b]) => a.score - b.score)
    .map(([clientId, { score, errors, warnings: warns, info }]) => {
      const client = clientMap.get(clientId);
      const name = client?.name ?? clientId;
      const clientWarnings = opts.warnings.filter((w) => w.client === clientId);
      const issueCount = errors + warns + info;

      const warningRows = clientWarnings.map((w) => {
        const icon = w.severity === "error" ? "&#10007;" : w.severity === "warning" ? "&#9888;" : "&#8505;";
        const color = w.severity === "error" ? "#ef4444" : w.severity === "warning" ? "#eab308" : "#3b82f6";
        return `<div style="padding:4px 0;border-bottom:1px solid #f1f1f1">
          <span style="color:${color}">${icon}</span>
          <strong>${escapeHtml(w.property)}</strong> — ${escapeHtml(w.message)}
          ${w.suggestion ? `<br><span style="color:#888;margin-left:20px">&rarr; ${escapeHtml(w.suggestion)}</span>` : ""}
        </div>`;
      }).join("");

      return `<div style="border:1px solid #e5e5e5;border-radius:8px;padding:16px;margin-bottom:16px">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px">
          <h3 style="margin:0;font-size:16px">${escapeHtml(name)}</h3>
          <span style="font-size:24px;font-weight:bold;color:${scoreColor(score)}">${score}</span>
        </div>
        <div style="font-size:13px;color:#888;margin-bottom:8px">${client?.engine ?? ""} &middot; ${client?.category ?? ""} &middot; ${issueCount} issue${issueCount === 1 ? "" : "s"}</div>
        ${clientWarnings.length > 0 ? `<div style="font-size:13px">${warningRows}</div>` : '<div style="color:#22c55e;font-size:13px">No issues</div>'}
      </div>`;
    }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Emailens Compatibility Report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 24px; background: #fafafa; color: #333; }
  .container { max-width: 900px; margin: 0 auto; }
  .header { text-align: center; margin-bottom: 32px; }
  .header h1 { margin: 0 0 8px; font-size: 24px; }
  .overall { font-size: 48px; font-weight: bold; }
  .subtitle { color: #888; font-size: 14px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(400px, 1fr)); gap: 16px; }
  .footer { text-align: center; margin-top: 32px; color: #aaa; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Emailens Compatibility Report</h1>
    <div class="overall" style="color:${scoreColor(overallScore)}">${overallScore}/100</div>
    <div class="subtitle">${Object.keys(opts.scores).length} clients analyzed &middot; ${opts.warnings.length} total issues</div>
  </div>
  <div class="grid">
    ${clientCards}
  </div>
  <div class="footer">
    Generated by <a href="https://github.com/emailens/cli" style="color:#888">@emailens/cli</a>
  </div>
</div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
